# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Update README.md

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'  

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
    
#     - name: UPDATE README.md
#       run: date >> README.md
  
#     - name: git commit
#       run: |
#         git config --local user.email "y4asse@users.noreply.github.com"
#         git config --local user.name "y4asse"
#         git log -1
#         git add README.md
#         git commit -m "Update README"
#         git push origin main

